version: "3.6"

services:
  minio1:
    image: minio/minio:RELEASE.2020-01-16T22-40-29Z
    container_name: minio1
    volumes:
      - data1-1:/data1
      - data1-2:/data2
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server http://minio{1...2}/data{1...2}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
  minio2:
    image: minio/minio:RELEASE.2020-01-16T22-40-29Z
    container_name: minio2
    volumes:
      - data2-1:/data1
      - data2-2:/data2
    ports:
      - "9001:9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server http://minio{1...2}/data{1...2}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
  redis:
    image: redis
    container_name: redis
    ports:
      - 6379:6379
  db:
    image: postgres
    container_name: database
    restart: always
    environment:
      POSTGRES_USER: fessenden_usr
      POSTGRES_PASSWORD: fessenden_pwd
      POSTGRES_DB: fessenden
    volumes:
    - ./.data/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
  pgadmin:
    image: dockage/phppgadmin
    container_name: pgadmin
    ports:
      - 8080:80
    environment:
      PHP_PG_ADMIN_SERVER_HOST: db
      POSTGRES_PASSWORD: fessenden_pwd
      POSTGRES_DB: fessenden
volumes:
  data1-1:
  data1-2:
  data2-1:
  data2-2:
