# Generated by Django 2.2.9 on 2020-01-17 22:24

from django.db import migrations, models
import django.db.models.deletion
import easy_thumbnails.fields
import feeds.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('image', easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to=feeds.models.feed_cover_location)),
                ('url', models.URLField()),
                ('last_fetched_at', models.DateTimeField(blank=True, null=True, verbose_name='Last fetch date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('content', models.TextField(blank=True)),
                ('published_at', models.DateTimeField()),
                ('url', models.URLField()),
                ('guid', models.CharField(max_length=200, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='feeds.Feed')),
            ],
        ),
    ]
