# Generated by Django 2.2.9 on 2020-01-17 22:49

from django.db import migrations, models
import django.db.models.deletion
import feeds.models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='episode',
            old_name='content',
            new_name='description_html',
        ),
        migrations.RenameField(
            model_name='episode',
            old_name='url',
            new_name='link',
        ),
        migrations.RenameField(
            model_name='feed',
            old_name='image',
            new_name='cover',
        ),
        migrations.RenameField(
            model_name='feed',
            old_name='url',
            new_name='feed_url',
        ),
        migrations.AddField(
            model_name='episode',
            name='subtitle',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='episode',
            name='total_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='feed',
            name='link',
            field=models.URLField(default='ddd'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Enclosure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('size', models.IntegerField(default=0)),
                ('mime_type', models.CharField(blank=True, max_length=36)),
                ('content', models.FileField(blank=True, null=True, upload_to=feeds.models.feed_enclosure_location)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enclosures', to='feeds.Episode')),
            ],
        ),
    ]
