# Generated by Django 2.2.9 on 2020-01-17 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0002_auto_20200117_2249'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='episode',
            options={'ordering': ['-published_at']},
        ),
        migrations.AlterField(
            model_name='enclosure',
            name='url',
            field=models.URLField(unique=True),
        ),
    ]
