# Generated by Django 2.2.9 on 2020-01-03 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0004_auto_20200103_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='url',
            field=models.URLField(),
        ),
    ]
